-- 003_regime.sql
-- Regime scoring snapshots

CREATE TABLE IF NOT EXISTS regime_snapshots (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scored_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    -- Composite regime
    composite_score         NUMERIC(5,4) NOT NULL,  -- -1.0 to +1.0
    regime                  TEXT NOT NULL CHECK (regime IN ('RISK_ON', 'NEUTRAL', 'RISK_OFF')),
    -- Per-dimension aggregate scores
    dim_macro_regime        NUMERIC(5,4),
    dim_micro_levels        NUMERIC(5,4),
    dim_options_flow        NUMERIC(5,4),
    dim_timing              NUMERIC(5,4),
    -- Per-analytical-layer scores
    layer_global_liquidity  NUMERIC(5,4),
    layer_macro_regime      NUMERIC(5,4),
    layer_market_structure  NUMERIC(5,4),
    layer_cycle_sentiment   NUMERIC(5,4),
    layer_options_flow      NUMERIC(5,4),
    layer_macro_to_micro    NUMERIC(5,4),
    -- Source participation
    sources_scored          TEXT[] NOT NULL DEFAULT '{}',
    sources_excluded        TEXT[] NOT NULL DEFAULT '{}',   -- stale/missing
    notes_used_count        INTEGER NOT NULL DEFAULT 0,
    -- Confidence: 0.0–1.0 based on source coverage and recency
    confidence              NUMERIC(3,2) NOT NULL DEFAULT 0.50,
    -- Narrative generated by AI
    narrative               TEXT,
    ai_model                TEXT,
    -- Prior regime for change detection
    prior_regime            TEXT CHECK (prior_regime IN ('RISK_ON', 'NEUTRAL', 'RISK_OFF')),
    regime_changed          BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_regime_scored_at ON regime_snapshots (scored_at DESC);
CREATE INDEX IF NOT EXISTS idx_regime_regime    ON regime_snapshots (regime);

-- Per-source regime contributions (detail rows for each snapshot)
CREATE TABLE IF NOT EXISTS regime_source_scores (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    snapshot_id         UUID NOT NULL REFERENCES regime_snapshots(id) ON DELETE CASCADE,
    source_id           TEXT NOT NULL REFERENCES sources(id),
    -- Weighted contribution scores for this source
    score_macro_regime  NUMERIC(5,4),
    score_micro_levels  NUMERIC(5,4),
    score_options_flow  NUMERIC(5,4),
    score_timing        NUMERIC(5,4),
    composite_score     NUMERIC(5,4),
    -- Recency decay factor applied (0.0–1.0)
    decay_factor        NUMERIC(5,4) NOT NULL DEFAULT 1.00,
    -- Research notes included
    notes_count         INTEGER NOT NULL DEFAULT 0,
    most_recent_note_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_rss_snapshot ON regime_source_scores (snapshot_id);
CREATE INDEX IF NOT EXISTS idx_rss_source   ON regime_source_scores (source_id);

-- ─── Row Level Security ─────────────────────────────────────────────────────
ALTER TABLE public.regime_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.regime_source_scores ENABLE ROW LEVEL SECURITY;
